// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated class builder wrappers for type-safe field access.

/// Wrapper for the `ArmDef` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct ArmDefClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl ArmDefClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner
            .as_type()
            .expect("ArmDef is statically defined in .baml and should always have a type")
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `step` field builder.
    pub fn property_step(&self) -> ::baml::ClassPropertyBuilder {
        self.inner
            .get_property("step")
            .expect("ArmDef.step is statically defined in .baml and should always be present")
    }

    /// Access the `handler` field builder.
    pub fn property_handler(&self) -> ::baml::ClassPropertyBuilder {
        self.inner
            .get_property("handler")
            .expect("ArmDef.handler is statically defined in .baml and should always be present")
    }

    /// Access the `args` field builder.
    pub fn property_args(&self) -> ::baml::ClassPropertyBuilder {
        self.inner
            .get_property("args")
            .expect("ArmDef.args is statically defined in .baml and should always be present")
    }
}

/// Wrapper for the `AssessHealthOutput` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct AssessHealthOutputClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl AssessHealthOutputClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type().expect(
            "AssessHealthOutput is statically defined in .baml and should always have a type",
        )
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `status` field builder.
    pub fn property_status(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("status").expect(
            "AssessHealthOutput.status is statically defined in .baml and should always be present",
        )
    }

    /// Access the `confidence` field builder.
    pub fn property_confidence(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("confidence")
            .expect("AssessHealthOutput.confidence is statically defined in .baml and should always be present")
    }

    /// Access the `reason` field builder.
    pub fn property_reason(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("reason").expect(
            "AssessHealthOutput.reason is statically defined in .baml and should always be present",
        )
    }
}

/// Wrapper for the `BudgetDef` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct BudgetDefClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl BudgetDefClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner
            .as_type()
            .expect("BudgetDef is statically defined in .baml and should always have a type")
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `tokens` field builder.
    pub fn property_tokens(&self) -> ::baml::ClassPropertyBuilder {
        self.inner
            .get_property("tokens")
            .expect("BudgetDef.tokens is statically defined in .baml and should always be present")
    }

    /// Access the `calls` field builder.
    pub fn property_calls(&self) -> ::baml::ClassPropertyBuilder {
        self.inner
            .get_property("calls")
            .expect("BudgetDef.calls is statically defined in .baml and should always be present")
    }

    /// Access the `duration_ms` field builder.
    pub fn property_duration_ms(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("duration_ms").expect(
            "BudgetDef.duration_ms is statically defined in .baml and should always be present",
        )
    }

    /// Access the `cost_cents` field builder.
    pub fn property_cost_cents(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("cost_cents").expect(
            "BudgetDef.cost_cents is statically defined in .baml and should always be present",
        )
    }
}

/// Wrapper for the `ClassifyCIFailureOutput` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct ClassifyCIFailureOutputClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl ClassifyCIFailureOutputClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type().expect(
            "ClassifyCIFailureOutput is statically defined in .baml and should always have a type",
        )
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `kind` field builder.
    pub fn property_kind(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("kind")
            .expect("ClassifyCIFailureOutput.kind is statically defined in .baml and should always be present")
    }

    /// Access the `fix_type` field builder.
    pub fn property_fix_type(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("fix_type")
            .expect("ClassifyCIFailureOutput.fix_type is statically defined in .baml and should always be present")
    }

    /// Access the `suggested_fix` field builder.
    pub fn property_suggested_fix(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("suggested_fix")
            .expect("ClassifyCIFailureOutput.suggested_fix is statically defined in .baml and should always be present")
    }

    /// Access the `confidence` field builder.
    pub fn property_confidence(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("confidence")
            .expect("ClassifyCIFailureOutput.confidence is statically defined in .baml and should always be present")
    }

    /// Access the `new_pattern` field builder.
    pub fn property_new_pattern(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("new_pattern")
            .expect("ClassifyCIFailureOutput.new_pattern is statically defined in .baml and should always be present")
    }
}

/// Wrapper for the `ClassifyOutput` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct ClassifyOutputClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl ClassifyOutputClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner
            .as_type()
            .expect("ClassifyOutput is statically defined in .baml and should always have a type")
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `label` field builder.
    pub fn property_label(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("label").expect(
            "ClassifyOutput.label is statically defined in .baml and should always be present",
        )
    }

    /// Access the `confidence` field builder.
    pub fn property_confidence(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("confidence").expect(
            "ClassifyOutput.confidence is statically defined in .baml and should always be present",
        )
    }

    /// Access the `reasoning` field builder.
    pub fn property_reasoning(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("reasoning").expect(
            "ClassifyOutput.reasoning is statically defined in .baml and should always be present",
        )
    }
}

/// Wrapper for the `ClassifyProjectOutput` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct ClassifyProjectOutputClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl ClassifyProjectOutputClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type().expect(
            "ClassifyProjectOutput is statically defined in .baml and should always have a type",
        )
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `category` field builder.
    pub fn property_category(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("category")
            .expect("ClassifyProjectOutput.category is statically defined in .baml and should always be present")
    }

    /// Access the `confidence` field builder.
    pub fn property_confidence(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("confidence")
            .expect("ClassifyProjectOutput.confidence is statically defined in .baml and should always be present")
    }
}

/// Wrapper for the `DecomposeSpecOutput` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct DecomposeSpecOutputClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl DecomposeSpecOutputClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type().expect(
            "DecomposeSpecOutput is statically defined in .baml and should always have a type",
        )
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `tasks` field builder.
    pub fn property_tasks(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("tasks").expect(
            "DecomposeSpecOutput.tasks is statically defined in .baml and should always be present",
        )
    }
}

/// Wrapper for the `DelegateNode` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct DelegateNodeClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl DelegateNodeClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner
            .as_type()
            .expect("DelegateNode is statically defined in .baml and should always have a type")
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `delegate_handler` field builder.
    pub fn property_delegate_handler(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("delegate_handler")
            .expect("DelegateNode.delegate_handler is statically defined in .baml and should always be present")
    }

    /// Access the `name` field builder.
    pub fn property_name(&self) -> ::baml::ClassPropertyBuilder {
        self.inner
            .get_property("name")
            .expect("DelegateNode.name is statically defined in .baml and should always be present")
    }

    /// Access the `budget` field builder.
    pub fn property_budget(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("budget").expect(
            "DelegateNode.budget is statically defined in .baml and should always be present",
        )
    }
}

/// Wrapper for the `DescribeProjectOutput` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct DescribeProjectOutputClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl DescribeProjectOutputClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type().expect(
            "DescribeProjectOutput is statically defined in .baml and should always have a type",
        )
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `description` field builder.
    pub fn property_description(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("description")
            .expect("DescribeProjectOutput.description is statically defined in .baml and should always be present")
    }
}

/// Wrapper for the `Entity` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct EntityClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl EntityClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner
            .as_type()
            .expect("Entity is statically defined in .baml and should always have a type")
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `name` field builder.
    pub fn property_name(&self) -> ::baml::ClassPropertyBuilder {
        self.inner
            .get_property("name")
            .expect("Entity.name is statically defined in .baml and should always be present")
    }

    /// Access the `entity_type` field builder.
    pub fn property_entity_type(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("entity_type").expect(
            "Entity.entity_type is statically defined in .baml and should always be present",
        )
    }

    /// Access the `description` field builder.
    pub fn property_description(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("description").expect(
            "Entity.description is statically defined in .baml and should always be present",
        )
    }
}

/// Wrapper for the `ExtractEntitiesOutput` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct ExtractEntitiesOutputClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl ExtractEntitiesOutputClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type().expect(
            "ExtractEntitiesOutput is statically defined in .baml and should always have a type",
        )
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `entities` field builder.
    pub fn property_entities(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("entities")
            .expect("ExtractEntitiesOutput.entities is statically defined in .baml and should always be present")
    }
}

/// Wrapper for the `GenerateChangelogOutput` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct GenerateChangelogOutputClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl GenerateChangelogOutputClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type().expect(
            "GenerateChangelogOutput is statically defined in .baml and should always have a type",
        )
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `summary` field builder.
    pub fn property_summary(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("summary")
            .expect("GenerateChangelogOutput.summary is statically defined in .baml and should always be present")
    }

    /// Access the `highlights` field builder.
    pub fn property_highlights(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("highlights")
            .expect("GenerateChangelogOutput.highlights is statically defined in .baml and should always be present")
    }
}

/// Wrapper for the `JoinAllNode` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct JoinAllNodeClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl JoinAllNodeClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner
            .as_type()
            .expect("JoinAllNode is statically defined in .baml and should always have a type")
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `join_all` field builder.
    pub fn property_join_all(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("join_all").expect(
            "JoinAllNode.join_all is statically defined in .baml and should always be present",
        )
    }

    /// Access the `arms` field builder.
    pub fn property_arms(&self) -> ::baml::ClassPropertyBuilder {
        self.inner
            .get_property("arms")
            .expect("JoinAllNode.arms is statically defined in .baml and should always be present")
    }
}

/// Wrapper for the `PipeNode` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct PipeNodeClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl PipeNodeClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner
            .as_type()
            .expect("PipeNode is statically defined in .baml and should always have a type")
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `pipe` field builder.
    pub fn property_pipe(&self) -> ::baml::ClassPropertyBuilder {
        self.inner
            .get_property("pipe")
            .expect("PipeNode.pipe is statically defined in .baml and should always be present")
    }

    /// Access the `stages` field builder.
    pub fn property_stages(&self) -> ::baml::ClassPropertyBuilder {
        self.inner
            .get_property("stages")
            .expect("PipeNode.stages is statically defined in .baml and should always be present")
    }
}

/// Wrapper for the `PipelineDef` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct PipelineDefClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl PipelineDefClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner
            .as_type()
            .expect("PipelineDef is statically defined in .baml and should always have a type")
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `pipeline` field builder.
    pub fn property_pipeline(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("pipeline").expect(
            "PipelineDef.pipeline is statically defined in .baml and should always be present",
        )
    }

    /// Access the `budget` field builder.
    pub fn property_budget(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("budget").expect(
            "PipelineDef.budget is statically defined in .baml and should always be present",
        )
    }

    /// Access the `steps` field builder.
    pub fn property_steps(&self) -> ::baml::ClassPropertyBuilder {
        self.inner
            .get_property("steps")
            .expect("PipelineDef.steps is statically defined in .baml and should always be present")
    }
}

/// Wrapper for the `RouteBranch` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct RouteBranchClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl RouteBranchClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner
            .as_type()
            .expect("RouteBranch is statically defined in .baml and should always have a type")
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `range` field builder.
    pub fn property_range(&self) -> ::baml::ClassPropertyBuilder {
        self.inner
            .get_property("range")
            .expect("RouteBranch.range is statically defined in .baml and should always be present")
    }

    /// Access the `label` field builder.
    pub fn property_label(&self) -> ::baml::ClassPropertyBuilder {
        self.inner
            .get_property("label")
            .expect("RouteBranch.label is statically defined in .baml and should always be present")
    }

    /// Access the `handler` field builder.
    pub fn property_handler(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("handler").expect(
            "RouteBranch.handler is statically defined in .baml and should always be present",
        )
    }

    /// Access the `args` field builder.
    pub fn property_args(&self) -> ::baml::ClassPropertyBuilder {
        self.inner
            .get_property("args")
            .expect("RouteBranch.args is statically defined in .baml and should always be present")
    }
}

/// Wrapper for the `RouteNode` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct RouteNodeClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl RouteNodeClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner
            .as_type()
            .expect("RouteNode is statically defined in .baml and should always have a type")
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `route_on_confidence` field builder.
    pub fn property_route_on_confidence(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("route_on_confidence")
            .expect("RouteNode.route_on_confidence is statically defined in .baml and should always be present")
    }

    /// Access the `value` field builder.
    pub fn property_value(&self) -> ::baml::ClassPropertyBuilder {
        self.inner
            .get_property("value")
            .expect("RouteNode.value is statically defined in .baml and should always be present")
    }

    /// Access the `routes` field builder.
    pub fn property_routes(&self) -> ::baml::ClassPropertyBuilder {
        self.inner
            .get_property("routes")
            .expect("RouteNode.routes is statically defined in .baml and should always be present")
    }
}

/// Wrapper for the `SpeculateNode` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct SpeculateNodeClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl SpeculateNodeClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner
            .as_type()
            .expect("SpeculateNode is statically defined in .baml and should always have a type")
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `speculate` field builder.
    pub fn property_speculate(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("speculate").expect(
            "SpeculateNode.speculate is statically defined in .baml and should always be present",
        )
    }

    /// Access the `mode` field builder.
    pub fn property_mode(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("mode").expect(
            "SpeculateNode.mode is statically defined in .baml and should always be present",
        )
    }

    /// Access the `arms` field builder.
    pub fn property_arms(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("arms").expect(
            "SpeculateNode.arms is statically defined in .baml and should always be present",
        )
    }
}

/// Wrapper for the `StepDef` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct StepDefClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl StepDefClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner
            .as_type()
            .expect("StepDef is statically defined in .baml and should always have a type")
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `step` field builder.
    pub fn property_step(&self) -> ::baml::ClassPropertyBuilder {
        self.inner
            .get_property("step")
            .expect("StepDef.step is statically defined in .baml and should always be present")
    }

    /// Access the `delegation` field builder.
    pub fn property_delegation(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("delegation").expect(
            "StepDef.delegation is statically defined in .baml and should always be present",
        )
    }

    /// Access the `pipe` field builder.
    pub fn property_pipe(&self) -> ::baml::ClassPropertyBuilder {
        self.inner
            .get_property("pipe")
            .expect("StepDef.pipe is statically defined in .baml and should always be present")
    }

    /// Access the `join_all` field builder.
    pub fn property_join_all(&self) -> ::baml::ClassPropertyBuilder {
        self.inner
            .get_property("join_all")
            .expect("StepDef.join_all is statically defined in .baml and should always be present")
    }

    /// Access the `route` field builder.
    pub fn property_route(&self) -> ::baml::ClassPropertyBuilder {
        self.inner
            .get_property("route")
            .expect("StepDef.route is statically defined in .baml and should always be present")
    }

    /// Access the `speculate` field builder.
    pub fn property_speculate(&self) -> ::baml::ClassPropertyBuilder {
        self.inner
            .get_property("speculate")
            .expect("StepDef.speculate is statically defined in .baml and should always be present")
    }
}

/// Wrapper for the `StepNode` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct StepNodeClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl StepNodeClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner
            .as_type()
            .expect("StepNode is statically defined in .baml and should always have a type")
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `step` field builder.
    pub fn property_step(&self) -> ::baml::ClassPropertyBuilder {
        self.inner
            .get_property("step")
            .expect("StepNode.step is statically defined in .baml and should always be present")
    }

    /// Access the `handler` field builder.
    pub fn property_handler(&self) -> ::baml::ClassPropertyBuilder {
        self.inner
            .get_property("handler")
            .expect("StepNode.handler is statically defined in .baml and should always be present")
    }

    /// Access the `args` field builder.
    pub fn property_args(&self) -> ::baml::ClassPropertyBuilder {
        self.inner
            .get_property("args")
            .expect("StepNode.args is statically defined in .baml and should always be present")
    }
}

/// Wrapper for the `SuggestRelatedOutput` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct SuggestRelatedOutputClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl SuggestRelatedOutputClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type().expect(
            "SuggestRelatedOutput is statically defined in .baml and should always have a type",
        )
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `related` field builder.
    pub fn property_related(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("related")
            .expect("SuggestRelatedOutput.related is statically defined in .baml and should always be present")
    }
}

/// Wrapper for the `SummarizeOutput` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct SummarizeOutputClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl SummarizeOutputClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner
            .as_type()
            .expect("SummarizeOutput is statically defined in .baml and should always have a type")
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `summary` field builder.
    pub fn property_summary(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("summary").expect(
            "SummarizeOutput.summary is statically defined in .baml and should always be present",
        )
    }

    /// Access the `key_points` field builder.
    pub fn property_key_points(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("key_points")
            .expect("SummarizeOutput.key_points is statically defined in .baml and should always be present")
    }

    /// Access the `word_count` field builder.
    pub fn property_word_count(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("word_count")
            .expect("SummarizeOutput.word_count is statically defined in .baml and should always be present")
    }
}

/// Wrapper for the `Task` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct TaskClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl TaskClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner
            .as_type()
            .expect("Task is statically defined in .baml and should always have a type")
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `id` field builder.
    pub fn property_id(&self) -> ::baml::ClassPropertyBuilder {
        self.inner
            .get_property("id")
            .expect("Task.id is statically defined in .baml and should always be present")
    }

    /// Access the `name` field builder.
    pub fn property_name(&self) -> ::baml::ClassPropertyBuilder {
        self.inner
            .get_property("name")
            .expect("Task.name is statically defined in .baml and should always be present")
    }

    /// Access the `title` field builder.
    pub fn property_title(&self) -> ::baml::ClassPropertyBuilder {
        self.inner
            .get_property("title")
            .expect("Task.title is statically defined in .baml and should always be present")
    }

    /// Access the `description` field builder.
    pub fn property_description(&self) -> ::baml::ClassPropertyBuilder {
        self.inner
            .get_property("description")
            .expect("Task.description is statically defined in .baml and should always be present")
    }

    /// Access the `priority` field builder.
    pub fn property_priority(&self) -> ::baml::ClassPropertyBuilder {
        self.inner
            .get_property("priority")
            .expect("Task.priority is statically defined in .baml and should always be present")
    }

    /// Access the `status` field builder.
    pub fn property_status(&self) -> ::baml::ClassPropertyBuilder {
        self.inner
            .get_property("status")
            .expect("Task.status is statically defined in .baml and should always be present")
    }

    /// Access the `files` field builder.
    pub fn property_files(&self) -> ::baml::ClassPropertyBuilder {
        self.inner
            .get_property("files")
            .expect("Task.files is statically defined in .baml and should always be present")
    }
}
