// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated TypeBuilder wrappers for type-safe schema access.

mod classes;
mod enums;

pub use classes::*;
pub use enums::*;

/// TypeBuilder for dynamic type construction.
///
/// This wrapper provides access to the BAML TypeBuilder for creating
/// dynamic types at runtime. Use `TypeBuilder::new()` to create an instance.
///
/// Access schema-defined classes and enums via methods:
/// - `tb.ClassName()` returns the class builder
/// - `tb.EnumName()` returns the enum builder
#[derive(Clone)]
pub struct TypeBuilder {
    inner: ::std::sync::Arc<::baml::TypeBuilder>,
}

impl TypeBuilder {
    /// Create a new TypeBuilder for dynamic type construction.
    ///
    /// # Example
    /// ```ignore
    /// let tb = TypeBuilder::new();
    /// let my_enum = tb.add_enum("MyDynamicEnum")?;
    /// my_enum.add_value("Option1")?;
    /// ```
    pub fn new() -> Self {
        Self {
            inner: ::std::sync::Arc::new(super::runtime::get_runtime().new_type_builder()),
        }
    }

    /// Get reference to inner TypeBuilder for FFI calls.
    pub(crate) fn inner(&self) -> &::baml::TypeBuilder {
        &self.inner
    }

    // =========================================================================
    // Schema Class Accessors (1:1 with schema class names)
    // =========================================================================

    /// Access the `ArmDef` class builder.
    pub fn ArmDef(&self) -> ArmDefClassBuilder {
        ArmDefClassBuilder::new(
            self.inner
                .get_class("ArmDef")
                .expect("class ArmDef is defined in schema"),
        )
    }

    /// Access the `AssessHealthOutput` class builder.
    pub fn AssessHealthOutput(&self) -> AssessHealthOutputClassBuilder {
        AssessHealthOutputClassBuilder::new(
            self.inner
                .get_class("AssessHealthOutput")
                .expect("class AssessHealthOutput is defined in schema"),
        )
    }

    /// Access the `BudgetDef` class builder.
    pub fn BudgetDef(&self) -> BudgetDefClassBuilder {
        BudgetDefClassBuilder::new(
            self.inner
                .get_class("BudgetDef")
                .expect("class BudgetDef is defined in schema"),
        )
    }

    /// Access the `ClassifyCIFailureOutput` class builder.
    pub fn ClassifyCIFailureOutput(&self) -> ClassifyCIFailureOutputClassBuilder {
        ClassifyCIFailureOutputClassBuilder::new(
            self.inner
                .get_class("ClassifyCIFailureOutput")
                .expect("class ClassifyCIFailureOutput is defined in schema"),
        )
    }

    /// Access the `ClassifyOutput` class builder.
    pub fn ClassifyOutput(&self) -> ClassifyOutputClassBuilder {
        ClassifyOutputClassBuilder::new(
            self.inner
                .get_class("ClassifyOutput")
                .expect("class ClassifyOutput is defined in schema"),
        )
    }

    /// Access the `ClassifyProjectOutput` class builder.
    pub fn ClassifyProjectOutput(&self) -> ClassifyProjectOutputClassBuilder {
        ClassifyProjectOutputClassBuilder::new(
            self.inner
                .get_class("ClassifyProjectOutput")
                .expect("class ClassifyProjectOutput is defined in schema"),
        )
    }

    /// Access the `DecomposeSpecOutput` class builder.
    pub fn DecomposeSpecOutput(&self) -> DecomposeSpecOutputClassBuilder {
        DecomposeSpecOutputClassBuilder::new(
            self.inner
                .get_class("DecomposeSpecOutput")
                .expect("class DecomposeSpecOutput is defined in schema"),
        )
    }

    /// Access the `DelegateNode` class builder.
    pub fn DelegateNode(&self) -> DelegateNodeClassBuilder {
        DelegateNodeClassBuilder::new(
            self.inner
                .get_class("DelegateNode")
                .expect("class DelegateNode is defined in schema"),
        )
    }

    /// Access the `DescribeProjectOutput` class builder.
    pub fn DescribeProjectOutput(&self) -> DescribeProjectOutputClassBuilder {
        DescribeProjectOutputClassBuilder::new(
            self.inner
                .get_class("DescribeProjectOutput")
                .expect("class DescribeProjectOutput is defined in schema"),
        )
    }

    /// Access the `Entity` class builder.
    pub fn Entity(&self) -> EntityClassBuilder {
        EntityClassBuilder::new(
            self.inner
                .get_class("Entity")
                .expect("class Entity is defined in schema"),
        )
    }

    /// Access the `ExtractEntitiesOutput` class builder.
    pub fn ExtractEntitiesOutput(&self) -> ExtractEntitiesOutputClassBuilder {
        ExtractEntitiesOutputClassBuilder::new(
            self.inner
                .get_class("ExtractEntitiesOutput")
                .expect("class ExtractEntitiesOutput is defined in schema"),
        )
    }

    /// Access the `GenerateChangelogOutput` class builder.
    pub fn GenerateChangelogOutput(&self) -> GenerateChangelogOutputClassBuilder {
        GenerateChangelogOutputClassBuilder::new(
            self.inner
                .get_class("GenerateChangelogOutput")
                .expect("class GenerateChangelogOutput is defined in schema"),
        )
    }

    /// Access the `JoinAllNode` class builder.
    pub fn JoinAllNode(&self) -> JoinAllNodeClassBuilder {
        JoinAllNodeClassBuilder::new(
            self.inner
                .get_class("JoinAllNode")
                .expect("class JoinAllNode is defined in schema"),
        )
    }

    /// Access the `PipeNode` class builder.
    pub fn PipeNode(&self) -> PipeNodeClassBuilder {
        PipeNodeClassBuilder::new(
            self.inner
                .get_class("PipeNode")
                .expect("class PipeNode is defined in schema"),
        )
    }

    /// Access the `PipelineDef` class builder.
    pub fn PipelineDef(&self) -> PipelineDefClassBuilder {
        PipelineDefClassBuilder::new(
            self.inner
                .get_class("PipelineDef")
                .expect("class PipelineDef is defined in schema"),
        )
    }

    /// Access the `RouteBranch` class builder.
    pub fn RouteBranch(&self) -> RouteBranchClassBuilder {
        RouteBranchClassBuilder::new(
            self.inner
                .get_class("RouteBranch")
                .expect("class RouteBranch is defined in schema"),
        )
    }

    /// Access the `RouteNode` class builder.
    pub fn RouteNode(&self) -> RouteNodeClassBuilder {
        RouteNodeClassBuilder::new(
            self.inner
                .get_class("RouteNode")
                .expect("class RouteNode is defined in schema"),
        )
    }

    /// Access the `SpeculateNode` class builder.
    pub fn SpeculateNode(&self) -> SpeculateNodeClassBuilder {
        SpeculateNodeClassBuilder::new(
            self.inner
                .get_class("SpeculateNode")
                .expect("class SpeculateNode is defined in schema"),
        )
    }

    /// Access the `StepDef` class builder.
    pub fn StepDef(&self) -> StepDefClassBuilder {
        StepDefClassBuilder::new(
            self.inner
                .get_class("StepDef")
                .expect("class StepDef is defined in schema"),
        )
    }

    /// Access the `StepNode` class builder.
    pub fn StepNode(&self) -> StepNodeClassBuilder {
        StepNodeClassBuilder::new(
            self.inner
                .get_class("StepNode")
                .expect("class StepNode is defined in schema"),
        )
    }

    /// Access the `SuggestRelatedOutput` class builder.
    pub fn SuggestRelatedOutput(&self) -> SuggestRelatedOutputClassBuilder {
        SuggestRelatedOutputClassBuilder::new(
            self.inner
                .get_class("SuggestRelatedOutput")
                .expect("class SuggestRelatedOutput is defined in schema"),
        )
    }

    /// Access the `SummarizeOutput` class builder.
    pub fn SummarizeOutput(&self) -> SummarizeOutputClassBuilder {
        SummarizeOutputClassBuilder::new(
            self.inner
                .get_class("SummarizeOutput")
                .expect("class SummarizeOutput is defined in schema"),
        )
    }

    /// Access the `Task` class builder.
    pub fn Task(&self) -> TaskClassBuilder {
        TaskClassBuilder::new(
            self.inner
                .get_class("Task")
                .expect("class Task is defined in schema"),
        )
    }

    // =========================================================================
    // Schema Enum Accessors (1:1 with schema enum names)
    // =========================================================================

    // =========================================================================
    // Primitive Types (all infallible)
    // =========================================================================

    /// Get the string type.
    pub fn string(&self) -> ::baml::TypeDef {
        self.inner.string()
    }

    /// Get the int type.
    pub fn int(&self) -> ::baml::TypeDef {
        self.inner.int()
    }

    /// Get the float type.
    pub fn float(&self) -> ::baml::TypeDef {
        self.inner.float()
    }

    /// Get the bool type.
    pub fn bool(&self) -> ::baml::TypeDef {
        self.inner.bool()
    }

    /// Get the null type.
    pub fn null(&self) -> ::baml::TypeDef {
        self.inner.null()
    }

    // =========================================================================
    // Literal Types (all infallible)
    // =========================================================================

    /// Create a literal string type.
    pub fn literal_string(&self, value: &str) -> ::baml::TypeDef {
        self.inner.literal_string(value)
    }

    /// Create a literal int type.
    pub fn literal_int(&self, value: i64) -> ::baml::TypeDef {
        self.inner.literal_int(value)
    }

    /// Create a literal bool type.
    pub fn literal_bool(&self, value: bool) -> ::baml::TypeDef {
        self.inner.literal_bool(value)
    }

    // =========================================================================
    // Composite Types (all infallible)
    // =========================================================================

    /// Create a list type.
    pub fn list(&self, inner: &::baml::TypeDef) -> ::baml::TypeDef {
        self.inner.list(inner)
    }

    /// Create an optional type.
    pub fn optional(&self, inner: &::baml::TypeDef) -> ::baml::TypeDef {
        self.inner.optional(inner)
    }

    /// Create a map type.
    pub fn map(&self, key: &::baml::TypeDef, value: &::baml::TypeDef) -> ::baml::TypeDef {
        self.inner.map(key, value)
    }

    /// Create a union type.
    pub fn union(&self, types: &[&::baml::TypeDef]) -> ::baml::TypeDef {
        self.inner.union(types)
    }

    // =========================================================================
    // Schema Operations (fallible)
    // =========================================================================

    /// Add BAML schema definitions.
    pub fn add_baml(&self, baml_source: &str) -> ::std::result::Result<(), ::baml::BamlError> {
        self.inner.add_baml(baml_source)
    }

    /// Print the TypeBuilder state for debugging.
    pub fn print(&self) -> ::std::string::String {
        self.inner.print()
    }

    // =========================================================================
    // Dynamic Enum Operations
    // =========================================================================

    /// Add a new dynamic enum.
    pub fn add_enum(
        &self,
        name: &str,
    ) -> ::std::result::Result<::baml::EnumBuilder, ::baml::BamlError> {
        self.inner.add_enum(name)
    }

    /// Get an enum by name (returns None if not found).
    pub fn get_enum(&self, name: &str) -> ::std::option::Option<::baml::EnumBuilder> {
        self.inner.get_enum(name)
    }

    /// List all enums.
    pub fn list_enums(&self) -> ::std::vec::Vec<::baml::EnumBuilder> {
        self.inner.list_enums()
    }

    // =========================================================================
    // Dynamic Class Operations
    // =========================================================================

    /// Add a new dynamic class.
    pub fn add_class(
        &self,
        name: &str,
    ) -> ::std::result::Result<::baml::ClassBuilder, ::baml::BamlError> {
        self.inner.add_class(name)
    }

    /// Get a class by name (returns None if not found).
    pub fn get_class(&self, name: &str) -> ::std::option::Option<::baml::ClassBuilder> {
        self.inner.get_class(name)
    }

    /// List all classes.
    pub fn list_classes(&self) -> ::std::vec::Vec<::baml::ClassBuilder> {
        self.inner.list_classes()
    }
}

impl ::std::default::Default for TypeBuilder {
    fn default() -> Self {
        Self::new()
    }
}

impl ::std::fmt::Debug for TypeBuilder {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        f.debug_struct("TypeBuilder")
            .field("state", &self.print())
            .finish()
    }
}
