// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated streaming class types.
//!
//! These types are used during streaming to hold partial results.
//! Field types are already wrapped appropriately (Option, StreamState, etc.)

use super::*;
use crate::baml_client::types;
use baml::{__internal::serde::Serialize, BamlDecode};

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct ArmDef {
    pub step: Option<String>,

    pub handler: Option<String>,

    pub args: Option<std::collections::HashMap<String, String>>,
}

impl ::std::convert::AsRef<ArmDef> for ArmDef {
    fn as_ref(&self) -> &ArmDef {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct AssessHealthOutput {
    pub status: Option<String>,

    pub confidence: Option<f64>,

    pub reason: Option<String>,
}

impl ::std::convert::AsRef<AssessHealthOutput> for AssessHealthOutput {
    fn as_ref(&self) -> &AssessHealthOutput {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct BudgetDef {
    pub tokens: Option<i64>,

    pub calls: Option<i64>,

    pub duration_ms: Option<i64>,

    pub cost_cents: Option<i64>,
}

impl ::std::convert::AsRef<BudgetDef> for BudgetDef {
    fn as_ref(&self) -> &BudgetDef {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct ClassifyCIFailureOutput {
    pub kind: Option<String>,

    pub fix_type: Option<String>,

    pub suggested_fix: Option<String>,

    pub confidence: Option<f64>,

    pub new_pattern: Option<String>,
}

impl ::std::convert::AsRef<ClassifyCIFailureOutput> for ClassifyCIFailureOutput {
    fn as_ref(&self) -> &ClassifyCIFailureOutput {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct ClassifyOutput {
    pub label: Option<String>,

    pub confidence: Option<f64>,

    pub reasoning: Option<String>,
}

impl ::std::convert::AsRef<ClassifyOutput> for ClassifyOutput {
    fn as_ref(&self) -> &ClassifyOutput {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct ClassifyProjectOutput {
    pub category: Option<String>,

    pub confidence: Option<f64>,
}

impl ::std::convert::AsRef<ClassifyProjectOutput> for ClassifyProjectOutput {
    fn as_ref(&self) -> &ClassifyProjectOutput {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct DecomposeSpecOutput {
    pub tasks: Vec<Task>,
}

impl ::std::convert::AsRef<DecomposeSpecOutput> for DecomposeSpecOutput {
    fn as_ref(&self) -> &DecomposeSpecOutput {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct DelegateNode {
    pub delegate_handler: Option<String>,

    pub name: Option<String>,

    pub budget: Option<BudgetDef>,
}

impl ::std::convert::AsRef<DelegateNode> for DelegateNode {
    fn as_ref(&self) -> &DelegateNode {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct DescribeProjectOutput {
    pub description: Option<String>,
}

impl ::std::convert::AsRef<DescribeProjectOutput> for DescribeProjectOutput {
    fn as_ref(&self) -> &DescribeProjectOutput {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct Entity {
    pub name: Option<String>,

    pub entity_type: Option<String>,

    pub description: Option<String>,
}

impl ::std::convert::AsRef<Entity> for Entity {
    fn as_ref(&self) -> &Entity {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct ExtractEntitiesOutput {
    pub entities: Vec<Entity>,
}

impl ::std::convert::AsRef<ExtractEntitiesOutput> for ExtractEntitiesOutput {
    fn as_ref(&self) -> &ExtractEntitiesOutput {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct GenerateChangelogOutput {
    pub summary: Option<String>,

    pub highlights: Vec<String>,
}

impl ::std::convert::AsRef<GenerateChangelogOutput> for GenerateChangelogOutput {
    fn as_ref(&self) -> &GenerateChangelogOutput {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct JoinAllNode {
    pub join_all: Option<String>,

    pub arms: Vec<ArmDef>,
}

impl ::std::convert::AsRef<JoinAllNode> for JoinAllNode {
    fn as_ref(&self) -> &JoinAllNode {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct PipeNode {
    pub pipe: Option<String>,

    pub stages: Vec<ArmDef>,
}

impl ::std::convert::AsRef<PipeNode> for PipeNode {
    fn as_ref(&self) -> &PipeNode {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct PipelineDef {
    pub pipeline: Option<String>,

    pub budget: Option<BudgetDef>,

    pub steps: Vec<StepDef>,
}

impl ::std::convert::AsRef<PipelineDef> for PipelineDef {
    fn as_ref(&self) -> &PipelineDef {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct RouteBranch {
    pub range: Option<String>,

    pub label: Option<String>,

    pub handler: Option<String>,

    pub args: Option<std::collections::HashMap<String, String>>,
}

impl ::std::convert::AsRef<RouteBranch> for RouteBranch {
    fn as_ref(&self) -> &RouteBranch {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct RouteNode {
    pub route_on_confidence: Option<String>,

    pub value: Option<String>,

    pub routes: Vec<RouteBranch>,
}

impl ::std::convert::AsRef<RouteNode> for RouteNode {
    fn as_ref(&self) -> &RouteNode {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct SpeculateNode {
    pub speculate: Option<String>,

    pub mode: Option<String>,

    pub arms: Vec<ArmDef>,
}

impl ::std::convert::AsRef<SpeculateNode> for SpeculateNode {
    fn as_ref(&self) -> &SpeculateNode {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct StepDef {
    pub step: Option<StepNode>,

    pub delegation: Option<DelegateNode>,

    pub pipe: Option<PipeNode>,

    pub join_all: Option<JoinAllNode>,

    pub route: Option<RouteNode>,

    pub speculate: Option<SpeculateNode>,
}

impl ::std::convert::AsRef<StepDef> for StepDef {
    fn as_ref(&self) -> &StepDef {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct StepNode {
    pub step: Option<String>,

    pub handler: Option<String>,

    pub args: Option<std::collections::HashMap<String, String>>,
}

impl ::std::convert::AsRef<StepNode> for StepNode {
    fn as_ref(&self) -> &StepNode {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct SuggestRelatedOutput {
    pub related: Vec<String>,
}

impl ::std::convert::AsRef<SuggestRelatedOutput> for SuggestRelatedOutput {
    fn as_ref(&self) -> &SuggestRelatedOutput {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct SummarizeOutput {
    pub summary: Option<String>,

    pub key_points: Vec<String>,

    pub word_count: Option<i64>,
}

impl ::std::convert::AsRef<SummarizeOutput> for SummarizeOutput {
    fn as_ref(&self) -> &SummarizeOutput {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct Task {
    pub id: Option<String>,

    pub name: Option<String>,

    pub title: Option<String>,

    pub description: Option<String>,

    pub priority: Option<String>,

    pub status: Option<String>,

    pub files: Vec<String>,
}

impl ::std::convert::AsRef<Task> for Task {
    fn as_ref(&self) -> &Task {
        self
    }
}
