// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated streaming types (partial data during streaming).
//!
//! Full implementation coming in Phase 6.

mod classes;
mod type_aliases;
mod unions;

pub use classes::*;
pub use type_aliases::*;
pub use unions::*;

use baml::__internal::serde;

/// Streaming variants of types (all fields Optional).
#[derive(Debug, Clone, serde::Serialize)]
#[serde(crate = "::baml::__internal::serde", untagged)]
pub enum StreamTypes {
    ArmDef(ArmDef),

    AssessHealthOutput(AssessHealthOutput),

    BudgetDef(BudgetDef),

    ClassifyCIFailureOutput(ClassifyCIFailureOutput),

    ClassifyOutput(ClassifyOutput),

    ClassifyProjectOutput(ClassifyProjectOutput),

    DecomposeSpecOutput(DecomposeSpecOutput),

    DelegateNode(DelegateNode),

    DescribeProjectOutput(DescribeProjectOutput),

    Entity(Entity),

    ExtractEntitiesOutput(ExtractEntitiesOutput),

    GenerateChangelogOutput(GenerateChangelogOutput),

    JoinAllNode(JoinAllNode),

    PipeNode(PipeNode),

    PipelineDef(PipelineDef),

    RouteBranch(RouteBranch),

    RouteNode(RouteNode),

    SpeculateNode(SpeculateNode),

    StepDef(StepDef),

    StepNode(StepNode),

    SuggestRelatedOutput(SuggestRelatedOutput),

    SummarizeOutput(SummarizeOutput),

    Task(Task),
}

impl baml::KnownTypes for StreamTypes {
    fn as_any(&self) -> &dyn ::std::any::Any {
        self
    }

    fn type_name(&self) -> &'static str {
        match self {
            StreamTypes::ArmDef(_) => "ArmDef",

            StreamTypes::AssessHealthOutput(_) => "AssessHealthOutput",

            StreamTypes::BudgetDef(_) => "BudgetDef",

            StreamTypes::ClassifyCIFailureOutput(_) => "ClassifyCIFailureOutput",

            StreamTypes::ClassifyOutput(_) => "ClassifyOutput",

            StreamTypes::ClassifyProjectOutput(_) => "ClassifyProjectOutput",

            StreamTypes::DecomposeSpecOutput(_) => "DecomposeSpecOutput",

            StreamTypes::DelegateNode(_) => "DelegateNode",

            StreamTypes::DescribeProjectOutput(_) => "DescribeProjectOutput",

            StreamTypes::Entity(_) => "Entity",

            StreamTypes::ExtractEntitiesOutput(_) => "ExtractEntitiesOutput",

            StreamTypes::GenerateChangelogOutput(_) => "GenerateChangelogOutput",

            StreamTypes::JoinAllNode(_) => "JoinAllNode",

            StreamTypes::PipeNode(_) => "PipeNode",

            StreamTypes::PipelineDef(_) => "PipelineDef",

            StreamTypes::RouteBranch(_) => "RouteBranch",

            StreamTypes::RouteNode(_) => "RouteNode",

            StreamTypes::SpeculateNode(_) => "SpeculateNode",

            StreamTypes::StepDef(_) => "StepDef",

            StreamTypes::StepNode(_) => "StepNode",

            StreamTypes::SuggestRelatedOutput(_) => "SuggestRelatedOutput",

            StreamTypes::SummarizeOutput(_) => "SummarizeOutput",

            StreamTypes::Task(_) => "Task",
        }
    }
}

impl<'de> serde::Deserialize<'de> for StreamTypes {
    fn deserialize<D: serde::Deserializer<'de>>(
        _deserializer: D,
    ) -> ::std::result::Result<Self, D::Error> {
        ::std::result::Result::Err(serde::de::Error::custom(
            "StreamTypes is not deserializable, as we cannot disambiguate the type.",
        ))
    }
}
