// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated BAML types.

mod classes;
mod enums;
mod type_aliases;
mod unions;

pub use classes::*;
pub use enums::*;
pub use type_aliases::*;
pub use unions::*;

// Re-export types from baml runtime
use baml::__internal::serde;
pub use baml::{Audio, Image, Pdf, Video};
pub use baml::{Checked, StreamState};

/// All known types in this BAML project.
/// Serves as the compile-time type registry for BamlValue.
#[derive(Debug, Clone, serde::Serialize)]
#[serde(crate = "::baml::__internal::serde", untagged)]
pub enum Types {
    ArmDef(ArmDef),

    AssessHealthOutput(AssessHealthOutput),

    BudgetDef(BudgetDef),

    ClassifyCIFailureOutput(ClassifyCIFailureOutput),

    ClassifyOutput(ClassifyOutput),

    ClassifyProjectOutput(ClassifyProjectOutput),

    DecomposeSpecOutput(DecomposeSpecOutput),

    DelegateNode(DelegateNode),

    DescribeProjectOutput(DescribeProjectOutput),

    Entity(Entity),

    ExtractEntitiesOutput(ExtractEntitiesOutput),

    GenerateChangelogOutput(GenerateChangelogOutput),

    JoinAllNode(JoinAllNode),

    PipeNode(PipeNode),

    PipelineDef(PipelineDef),

    RouteBranch(RouteBranch),

    RouteNode(RouteNode),

    SpeculateNode(SpeculateNode),

    StepDef(StepDef),

    StepNode(StepNode),

    SuggestRelatedOutput(SuggestRelatedOutput),

    SummarizeOutput(SummarizeOutput),

    Task(Task),
}

impl ::baml::KnownTypes for Types {
    fn as_any(&self) -> &dyn ::std::any::Any {
        self
    }

    fn type_name(&self) -> &'static str {
        match self {
            Self::ArmDef(_) => "ArmDef",

            Self::AssessHealthOutput(_) => "AssessHealthOutput",

            Self::BudgetDef(_) => "BudgetDef",

            Self::ClassifyCIFailureOutput(_) => "ClassifyCIFailureOutput",

            Self::ClassifyOutput(_) => "ClassifyOutput",

            Self::ClassifyProjectOutput(_) => "ClassifyProjectOutput",

            Self::DecomposeSpecOutput(_) => "DecomposeSpecOutput",

            Self::DelegateNode(_) => "DelegateNode",

            Self::DescribeProjectOutput(_) => "DescribeProjectOutput",

            Self::Entity(_) => "Entity",

            Self::ExtractEntitiesOutput(_) => "ExtractEntitiesOutput",

            Self::GenerateChangelogOutput(_) => "GenerateChangelogOutput",

            Self::JoinAllNode(_) => "JoinAllNode",

            Self::PipeNode(_) => "PipeNode",

            Self::PipelineDef(_) => "PipelineDef",

            Self::RouteBranch(_) => "RouteBranch",

            Self::RouteNode(_) => "RouteNode",

            Self::SpeculateNode(_) => "SpeculateNode",

            Self::StepDef(_) => "StepDef",

            Self::StepNode(_) => "StepNode",

            Self::SuggestRelatedOutput(_) => "SuggestRelatedOutput",

            Self::SummarizeOutput(_) => "SummarizeOutput",

            Self::Task(_) => "Task",
        }
    }
}

impl<'de> serde::Deserialize<'de> for Types {
    fn deserialize<D: serde::Deserializer<'de>>(
        _deserializer: D,
    ) -> ::std::result::Result<Self, D::Error> {
        ::std::result::Result::Err(serde::de::Error::custom(
            "Types is not deserializable, as we cannot disambiguate the type.",
        ))
    }
}
