// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated class builder wrappers for type-safe field access.


/// Wrapper for the `ClassifyOutput` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct ClassifyOutputClassBuilder {
    inner: baml::ClassBuilder,
}

impl ClassifyOutputClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("ClassifyOutput is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `label` field builder.
    pub fn property_label(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("label")
            .expect("ClassifyOutput.label is statically defined in .baml and should always be present")
    }


    /// Access the `confidence` field builder.
    pub fn property_confidence(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("confidence")
            .expect("ClassifyOutput.confidence is statically defined in .baml and should always be present")
    }


    /// Access the `reasoning` field builder.
    pub fn property_reasoning(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("reasoning")
            .expect("ClassifyOutput.reasoning is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `Entity` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct EntityClassBuilder {
    inner: baml::ClassBuilder,
}

impl EntityClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("Entity is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `name` field builder.
    pub fn property_name(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("name")
            .expect("Entity.name is statically defined in .baml and should always be present")
    }


    /// Access the `entity_type` field builder.
    pub fn property_entity_type(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("entity_type")
            .expect("Entity.entity_type is statically defined in .baml and should always be present")
    }


    /// Access the `description` field builder.
    pub fn property_description(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("description")
            .expect("Entity.description is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `ExtractEntitiesOutput` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct ExtractEntitiesOutputClassBuilder {
    inner: baml::ClassBuilder,
}

impl ExtractEntitiesOutputClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("ExtractEntitiesOutput is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `entities` field builder.
    pub fn property_entities(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("entities")
            .expect("ExtractEntitiesOutput.entities is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `SummarizeOutput` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct SummarizeOutputClassBuilder {
    inner: baml::ClassBuilder,
}

impl SummarizeOutputClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("SummarizeOutput is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `summary` field builder.
    pub fn property_summary(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("summary")
            .expect("SummarizeOutput.summary is statically defined in .baml and should always be present")
    }


    /// Access the `key_points` field builder.
    pub fn property_key_points(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("key_points")
            .expect("SummarizeOutput.key_points is statically defined in .baml and should always be present")
    }


    /// Access the `word_count` field builder.
    pub fn property_word_count(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("word_count")
            .expect("SummarizeOutput.word_count is statically defined in .baml and should always be present")
    }

}

