// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com


//! Generated class types.

use baml::{BamlEncode, BamlDecode};
use super::*;




#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct ClassifyOutput {



    pub label: String,



    pub confidence: f64,



    pub reasoning: Option<String>,


}



impl AsRef<ClassifyOutput> for ClassifyOutput {
    fn as_ref(&self) -> &ClassifyOutput {
        self
    }
}




#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct Entity {



    pub name: String,



    pub entity_type: String,



    pub description: Option<String>,


}



impl AsRef<Entity> for Entity {
    fn as_ref(&self) -> &Entity {
        self
    }
}




#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct ExtractEntitiesOutput {



    pub entities: Vec<Entity>,


}



impl AsRef<ExtractEntitiesOutput> for ExtractEntitiesOutput {
    fn as_ref(&self) -> &ExtractEntitiesOutput {
        self
    }
}




#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct SummarizeOutput {



    pub summary: String,



    pub key_points: Vec<String>,



    pub word_count: i64,


}



impl AsRef<SummarizeOutput> for SummarizeOutput {
    fn as_ref(&self) -> &SummarizeOutput {
        self
    }
}

