// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Synchronous BAML client with function-object pattern.

use crate::baml_client::{
    runtime::{FunctionOptions, get_runtime},
    stream_types, types,
};
use baml::{BamlEncode, BamlError, StreamingCall};

// =============================================================================
// Convenience Builder Methods Macro
// =============================================================================

/// Implements convenience builder methods that delegate to `with_options`.
/// Requires the type to have:
/// - `options: FunctionOptions` field
/// - `fn with_options(&self, options: FunctionOptions) -> Self` method
macro_rules! impl_options_convenience_methods {
    ($name:ident) => {
        impl $name {
            pub fn with_collector(&self, collector: &baml::Collector) -> Self {
                self.with_options(self.options.clone().with_collector(collector))
            }

            pub fn with_collectors(&self, collectors: &[baml::Collector]) -> Self {
                self.with_options(self.options.clone().with_collectors(collectors))
            }

            pub fn with_cancellation_token(&self, token: Option<baml::CancellationToken>) -> Self {
                self.with_options(self.options.clone().with_cancellation_token(token))
            }

            pub fn with_type_builder(&self, tb: &super::super::type_builder::TypeBuilder) -> Self {
                self.with_options(self.options.clone().with_type_builder(tb))
            }

            pub fn with_env_var(&self, key: impl Into<String>, value: impl Into<String>) -> Self {
                self.with_options(self.options.clone().with_env_var(key, value))
            }

            pub fn with_tag(&self, key: impl Into<String>, value: impl Into<String>) -> Self {
                self.with_options(self.options.clone().with_tag(key, value))
            }

            pub fn with_client(&self, client_name: impl Into<String>) -> Self {
                self.with_options(self.options.clone().with_client(client_name))
            }

            pub fn with_client_registry(&self, registry: &baml::ClientRegistry) -> Self {
                self.with_options(self.options.clone().with_client_registry(registry))
            }

            pub fn with_on_tick<F>(&self, callback: F) -> Self
            where
                F: Fn(&baml::FunctionLog) + Send + Sync + 'static,
            {
                self.with_options(self.options.clone().with_on_tick(callback))
            }
        }
    };
}

// =============================================================================
// Function Struct Macro (generates per-function struct)
// =============================================================================

macro_rules! baml_function_sync {
    ($name:ident($($param:ident : $ptype:ty),* $(,)?) -> ($stream_ret:ty, $final_ret:ty)) => {
        #[derive(Clone)]
        pub struct $name {
            pub(crate) options: FunctionOptions,
        }

        impl $name {
            pub const fn new() -> Self {
                Self { options: FunctionOptions::new() }
            }

            fn with_options(&self, options: FunctionOptions) -> Self {
                Self { options }
            }

            // Terminal methods
            pub fn call(&self, $($param: $ptype),*) -> Result<$final_ret, BamlError> {
                let args = self.options.to_baml_args()
                    $(.arg(stringify!($param), $param.baml_encode()))*;
                get_runtime().call_function(stringify!($name), &args)
            }

            pub fn stream(&self, $($param: $ptype),*) -> Result<StreamingCall<$stream_ret, $final_ret>, BamlError> {
                let args = self.options.to_baml_args()
                    $(.arg(stringify!($param), $param.baml_encode()))*;
                get_runtime().call_function_stream(stringify!($name), &args)
            }

            pub fn parse(&self, response: &str) -> Result<$final_ret, BamlError> {
                get_runtime().parse(stringify!($name), response, false)
            }

            pub fn parse_stream(&self, response: &str) -> Result<$stream_ret, BamlError> {
                get_runtime().parse(stringify!($name), response, true)
            }

            pub fn build_request(&self, $($param: $ptype),*) -> Result<baml::HTTPRequest, BamlError> {
                let args = self.options.to_baml_args()
                    $(.arg(stringify!($param), $param.baml_encode()))*
                    .arg("stream", false);
                get_runtime().build_request(stringify!($name), &args)
            }

            pub fn build_request_stream(&self, $($param: $ptype),*) -> Result<baml::HTTPRequest, BamlError> {
                let args = self.options.to_baml_args()
                    $(.arg(stringify!($param), $param.baml_encode()))*
                    .arg("stream", true);
                get_runtime().build_request_stream(stringify!($name), &args)
            }
        }

        // Builder convenience methods (separate impl block via macro)
        impl_options_convenience_methods!($name);
    };
}

// =============================================================================
// Generate function structs
// =============================================================================

baml_function_sync!(AssessHealth(name: impl AsRef<str> + BamlEncode, pushed_at: impl AsRef<str> + BamlEncode, commit_dates: &[String], open_issues: Option<i64>, ) -> (stream_types::AssessHealthOutput, types::AssessHealthOutput));

baml_function_sync!(Classify(text: impl AsRef<str> + BamlEncode, labels: &[String], ) -> (stream_types::ClassifyOutput, types::ClassifyOutput));

baml_function_sync!(ClassifyCIFailure(failure_output: impl AsRef<str> + BamlEncode, known_patterns: &[String], ) -> (stream_types::ClassifyCIFailureOutput, types::ClassifyCIFailureOutput));

baml_function_sync!(ClassifyProject(name: impl AsRef<str> + BamlEncode, description: Option<impl AsRef<str> + BamlEncode>, language: Option<impl AsRef<str> + BamlEncode>, topics: &[String], commits: &[String], ) -> (stream_types::ClassifyProjectOutput, types::ClassifyProjectOutput));

baml_function_sync!(DecomposeSpec(text: impl AsRef<str> + BamlEncode, ) -> (stream_types::DecomposeSpecOutput, types::DecomposeSpecOutput));

baml_function_sync!(DescribeProject(name: impl AsRef<str> + BamlEncode, language: Option<impl AsRef<str> + BamlEncode>, readme: Option<impl AsRef<str> + BamlEncode>, commits: &[String], ) -> (stream_types::DescribeProjectOutput, types::DescribeProjectOutput));

baml_function_sync!(ExtractEntities(text: impl AsRef<str> + BamlEncode, ) -> (stream_types::ExtractEntitiesOutput, types::ExtractEntitiesOutput));

baml_function_sync!(GenerateChangelog(name: impl AsRef<str> + BamlEncode, commits: &[String], ) -> (stream_types::GenerateChangelogOutput, types::GenerateChangelogOutput));

baml_function_sync!(GeneratePipeline(goal: impl AsRef<str> + BamlEncode, available_handlers: &[String], constraints: Option<impl AsRef<str> + BamlEncode>, ) -> (stream_types::PipelineDef, types::PipelineDef));

baml_function_sync!(SuggestRelated(name: impl AsRef<str> + BamlEncode, description: Option<impl AsRef<str> + BamlEncode>, category: Option<impl AsRef<str> + BamlEncode>, all_projects: &[String], ) -> (stream_types::SuggestRelatedOutput, types::SuggestRelatedOutput));

baml_function_sync!(Summarize(text: impl AsRef<str> + BamlEncode, max_sentences: i64, ) -> (stream_types::SummarizeOutput, types::SummarizeOutput));

// =============================================================================
// Client Struct
// =============================================================================

#[derive(Clone)]
pub struct BamlSyncClient {
    options: FunctionOptions,

    pub AssessHealth: AssessHealth,

    pub Classify: Classify,

    pub ClassifyCIFailure: ClassifyCIFailure,

    pub ClassifyProject: ClassifyProject,

    pub DecomposeSpec: DecomposeSpec,

    pub DescribeProject: DescribeProject,

    pub ExtractEntities: ExtractEntities,

    pub GenerateChangelog: GenerateChangelog,

    pub GeneratePipeline: GeneratePipeline,

    pub SuggestRelated: SuggestRelated,

    pub Summarize: Summarize,
}

impl BamlSyncClient {
    pub const fn new() -> Self {
        Self {
            options: FunctionOptions::new(),

            AssessHealth: AssessHealth::new(),

            Classify: Classify::new(),

            ClassifyCIFailure: ClassifyCIFailure::new(),

            ClassifyProject: ClassifyProject::new(),

            DecomposeSpec: DecomposeSpec::new(),

            DescribeProject: DescribeProject::new(),

            ExtractEntities: ExtractEntities::new(),

            GenerateChangelog: GenerateChangelog::new(),

            GeneratePipeline: GeneratePipeline::new(),

            SuggestRelated: SuggestRelated::new(),

            Summarize: Summarize::new(),
        }
    }

    /// Apply options to all functions. Returns a new client with the options set.
    pub fn with_options(&self, options: FunctionOptions) -> Self {
        Self {
            options: options.clone(),

            AssessHealth: AssessHealth {
                options: options.clone(),
            },

            Classify: Classify {
                options: options.clone(),
            },

            ClassifyCIFailure: ClassifyCIFailure {
                options: options.clone(),
            },

            ClassifyProject: ClassifyProject {
                options: options.clone(),
            },

            DecomposeSpec: DecomposeSpec {
                options: options.clone(),
            },

            DescribeProject: DescribeProject {
                options: options.clone(),
            },

            ExtractEntities: ExtractEntities {
                options: options.clone(),
            },

            GenerateChangelog: GenerateChangelog {
                options: options.clone(),
            },

            GeneratePipeline: GeneratePipeline {
                options: options.clone(),
            },

            SuggestRelated: SuggestRelated {
                options: options.clone(),
            },

            Summarize: Summarize {
                options: options.clone(),
            },
        }
    }
}

// Builder convenience methods
impl_options_convenience_methods!(BamlSyncClient);

pub static B: BamlSyncClient = BamlSyncClient::new();
