// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com


//! Generated streaming class types.
//!
//! These types are used during streaming to hold partial results.
//! Field types are already wrapped appropriately (Option, StreamState, etc.)

use baml::BamlDecode;
use crate::baml_client::types;
use super::*;





#[derive(Debug, Clone, Default, BamlDecode)]

pub struct ClassifyOutput {



    pub label: Option<String>,



    pub confidence: Option<f64>,



    pub reasoning: Option<String>,


}



impl AsRef<ClassifyOutput> for ClassifyOutput {
    fn as_ref(&self) -> &ClassifyOutput {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct Entity {



    pub name: Option<String>,



    pub entity_type: Option<String>,



    pub description: Option<String>,


}



impl AsRef<Entity> for Entity {
    fn as_ref(&self) -> &Entity {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct ExtractEntitiesOutput {



    pub entities: Vec<Entity>,


}



impl AsRef<ExtractEntitiesOutput> for ExtractEntitiesOutput {
    fn as_ref(&self) -> &ExtractEntitiesOutput {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct SummarizeOutput {



    pub summary: Option<String>,



    pub key_points: Vec<String>,



    pub word_count: Option<i64>,


}



impl AsRef<SummarizeOutput> for SummarizeOutput {
    fn as_ref(&self) -> &SummarizeOutput {
        self
    }
}

