[package]
name = "crux-stdlib"
description = "Standard library handlers for crux-script pipelines (fs, git, json, text, ctrl)"
version.workspace = true
edition.workspace = true
readme = "../../README.md"
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
crux-runtime = { workspace = true } #unified
crux-script = { workspace = true } #unified
glob = { workspace = true } #unified
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
